return {
  -- "nvimtools/none-ls.nvim",
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  -- },
  -- config = function()
  --   local null_ls = require "null-ls"
  --
  --   local formatting = null_ls.builtins.formatting
  --   local diagnostics = null_ls.builtins.diagnostics
  --   local completion = null_ls.builtins.completion
  --
  --   null_ls.setup {
  --     debug = false,
  --     sources = {
  --       formatting.stylua,
  --       formatting.prettier,
  --       formatting.black,
  --       diagnostics.erb_lint,
  --       diagnostics.rubocop,
  --       formatting.rubocop,
  --       completion.spell,
  --       -- null_ls.builtins.diagnostics.flake8,
  --       -- null_ls.builtins.diagnostics.spell,
  --     },
  --   }
  -- end,
}
