return {
  filetypes = { "php", "blade" },
  settings = {
    intelephense = {
      files = {
        maxSize = 5000000,
      },
      -- CodeIgniter 4 is Composer-based; intelephense indexes vendor/ automatically.
      -- These stubs cover PHP core + all standard extensions used in CI4 projects.
      stubs = {
        "apache",
        "bcmath",
        "bz2",
        "calendar",
        "Core",
        "ctype",
        "curl",
        "date",
        "dom",
        "exif",
        "fileinfo",
        "filter",
        "ftp",
        "gd",
        "gettext",
        "gmp",
        "hash",
        "iconv",
        "intl",
        "json",
        "libxml",
        "mbstring",
        "meta",
        "mysqli",
        "openssl",
        "pcntl",
        "pcre",
        "PDO",
        "pdo_mysql",
        "pdo_pgsql",
        "pdo_sqlite",
        "pgsql",
        "Phar",
        "posix",
        "readline",
        "Reflection",
        "session",
        "SimpleXML",
        "soap",
        "sockets",
        "sodium",
        "SPL",
        "sqlite3",
        "standard",
        "superglobals",
        "tokenizer",
        "xml",
        "xmlreader",
        "xmlwriter",
        "xsl",
        "zip",
        "zlib",
      },
    },
  },
}
